name: Terraform Deploy RDS to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      # Inicializar, validar e aplicar o Terraform para o diretório terraform
      - name: Initialize Terraform for Rds
        working-directory: terraform
        run: terraform init

      - name: Validate Terraform for Rds
        working-directory: terraform
        run: terraform validate

      - name: Plan Terraform for Rds
        working-directory: terraform
        run: terraform plan -out=rds

      - name: Apply Terraform for Rds
        working-directory: terraform
        run: terraform apply -auto-approve rds
